# Redis Stream channels
PRICE_TICK     = "price:tick"
SIGNAL_NEW     = "signal:new"
ML_SIGNAL      = "ml:signal"
ORDER_PLACED   = "order:placed"
ORDER_FILLED   = "order:filled"
ORDER_REJECTED = "order:rejected"
RISK_UPDATE    = "risk:update"
RISK_ALERT     = "risk:alert"
ORCH_DECISION  = "orchestrator:decision"
SENTIMENT_UPDATE = "sentiment:update"
TRADE_CLOSED     = "trade:closed"
POSITION_UPDATE  = "position:update"
PERF_UPDATE      = "perf:update"
